/**
 * SQLite storage adapter (classic mode, dedup mode, streaming, object-storage tiering).
 *
 * Uses the EXACT schema the Python package's SQLiteBackend creates, so a Node app and a
 * Python app can share one `.db` file: ids are TEXT UUIDs generated by the application, timestamps are
 * ISO-8601 TEXT, classic rows say storage_backend='sqlite', and tiered rows point at object storage.
 *
 * HOW THIS DIFFERS FROM THE POSTGRES ADAPTER (and why)
 *
 *  - The driver (`better-sqlite3`) is SYNCHRONOUS. Every operation here is async only in signature: the
 *    SQLite call itself runs on the event loop and returns almost immediately (it is a local file).
 *    Because a blocked synchronous call would freeze the whole process, lock contention is never waited
 *    out inside the driver. Each attempt uses a ~25 ms busy timeout and BUSY errors are retried here with
 *    ASYNC sleeps, up to `busyTimeoutMs` in total, so the event loop stays free.
 *  - One long-lived connection serves all normal operations. Each unit of work runs to completion
 *    synchronously inside BEGIN IMMEDIATE ... COMMIT, so concurrent requests can never interleave inside
 *    a transaction.
 *  - Tiering awaits a network upload while holding a write transaction, so it uses its OWN dedicated
 *    connection (otherwise other requests would run inside that open transaction and a rollback would
 *    erase their writes). SQLite has no per-row locks: BEGIN IMMEDIATE locks the WHOLE DATABASE for the
 *    duration of the upload. Writes from other PROCESSES wait (and time out after busyTimeoutMs); writes
 *    from this process queue behind an in-process async lock. Reads are never blocked (WAL).
 *  - WAL mode is a durable file-level setting. It is set at most once per backend instance, and only if
 *    the file is not already in WAL mode (re-issuing it on every connection caused real lock contention
 *    on Windows in the Python package).
 *  - Streaming reads use ranged `substr(data, offset, length)` queries (better-sqlite3 has no incremental
 *    blob handle). A row deleted mid-stream therefore raises StorageError, exactly like Postgres. (The
 *    Python SYNC SQLite adapter instead keeps streaming from a WAL snapshot; pass your own `connection`
 *    inside a transaction here if you need that.) SQLite still reads the whole blob per chunk, in native
 *    memory: this bounds Node-side memory only.
 */
import { randomUUID } from "node:crypto";
import { StorageError } from "../errors.js";
import type { ObjectStorageLike } from "../object-storage.js";
import type {
  Connection,
  OperationEvent,
  PreparedRow,
  SqliteDatabaseLike,
} from "../types.js";
import type {
  CallOptions,
  StorageBackend,
  StoredRecord,
  StoredRecordMetadata,
  StreamOptions,
} from "./base.js";
import {
  hydrateRow,
  isValidId,
  mapLimit,
  msg,
  sleep,
  streamFromObjectStorage,
  tieredWithoutStorage,
  wrap,
} from "./shared.js";

// ---- schema (identical to the Python package) -------------------------------------------------

const SCHEMA = `
CREATE TABLE IF NOT EXISTS zerobucket_images (
    id                  TEXT PRIMARY KEY,
    data                BLOB,
    mime_type           TEXT NOT NULL,
    original_filename   TEXT,
    size_bytes          INTEGER NOT NULL,
    width               INTEGER,
    height              INTEGER,
    checksum_sha256     TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    storage_backend     TEXT NOT NULL DEFAULT 'sqlite',
    object_storage_bucket TEXT,
    object_storage_key  TEXT,
    CHECK (
        (storage_backend = 'sqlite'
            AND data IS NOT NULL
            AND object_storage_key IS NULL
            AND object_storage_bucket IS NULL)
        OR
        (storage_backend = 'object_storage'
            AND data IS NULL
            AND object_storage_key IS NOT NULL
            AND object_storage_bucket IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS idx_zerobucket_checksum ON zerobucket_images (checksum_sha256);
CREATE INDEX IF NOT EXISTS idx_zerobucket_created_at ON zerobucket_images (created_at);
`;

const DEDUP_SCHEMA = `
CREATE TABLE IF NOT EXISTS zerobucket_blobs (
    checksum_sha256     TEXT PRIMARY KEY,
    data                BLOB NOT NULL,
    mime_type           TEXT NOT NULL,
    size_bytes          INTEGER NOT NULL,
    width               INTEGER,
    height              INTEGER,
    ref_count           INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS zerobucket_image_refs (
    id                  TEXT PRIMARY KEY,
    checksum_sha256     TEXT NOT NULL REFERENCES zerobucket_blobs(checksum_sha256),
    original_filename   TEXT,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_zerobucket_image_refs_checksum ON zerobucket_image_refs (checksum_sha256);
CREATE INDEX IF NOT EXISTS idx_zerobucket_image_refs_created_at ON zerobucket_image_refs (created_at);
`;

// ---- SQL --------------------------------------------------------------------------------------

const COLS = `id, data, mime_type, original_filename, size_bytes, width, height, checksum_sha256, storage_backend, object_storage_bucket, object_storage_key`;
const INSERT = `INSERT INTO zerobucket_images (id, data, mime_type, original_filename, size_bytes, width, height, checksum_sha256, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`;
const SELECT_FULL = `SELECT ${COLS} FROM zerobucket_images WHERE id = ?`;
const selectMany = (n: number) =>
  `SELECT ${COLS} FROM zerobucket_images WHERE id IN (${placeholders(n)})`;
const SELECT_METADATA = `SELECT id, mime_type, original_filename, size_bytes, width, height, checksum_sha256 FROM zerobucket_images WHERE id = ?`;
const STREAM_INFO = `SELECT size_bytes, storage_backend, object_storage_key FROM zerobucket_images WHERE id = ?`;
const CHUNK = `SELECT substr(data, ?, ?) AS chunk FROM zerobucket_images WHERE id = ?`;
const EXISTS = `SELECT 1 FROM zerobucket_images WHERE id = ?`;
const DELETE_ONE = `DELETE FROM zerobucket_images WHERE id = ? RETURNING storage_backend, object_storage_key`;
const deleteMany = (n: number) =>
  `DELETE FROM zerobucket_images WHERE id IN (${placeholders(n)}) RETURNING id, storage_backend, object_storage_key`;
const SELECT_FOR_TIERING = `SELECT data, mime_type, size_bytes, storage_backend FROM zerobucket_images WHERE id = ?`;
const UPDATE_AFTER_TIERING = `UPDATE zerobucket_images SET data = NULL, storage_backend = 'object_storage', object_storage_bucket = ?, object_storage_key = ?, updated_at = ? WHERE id = ?`;

// dedup. Reads are aliased to the classic column names so one row mapper serves both modes.
const D_FROM = `FROM zerobucket_image_refs r JOIN zerobucket_blobs b ON r.checksum_sha256 = b.checksum_sha256`;
const D_COLS = `r.id AS id, b.data AS data, b.mime_type AS mime_type, r.original_filename AS original_filename, b.size_bytes AS size_bytes, b.width AS width, b.height AS height, r.checksum_sha256 AS checksum_sha256, 'sqlite' AS storage_backend, NULL AS object_storage_bucket, NULL AS object_storage_key`;
const D_UPSERT = `INSERT INTO zerobucket_blobs (checksum_sha256, data, mime_type, size_bytes, width, height, ref_count, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (checksum_sha256) DO UPDATE SET ref_count = ref_count + excluded.ref_count`;
const D_INSERT_REF = `INSERT INTO zerobucket_image_refs (id, checksum_sha256, original_filename, created_at, updated_at) VALUES (?, ?, ?, ?, ?)`;
const D_SELECT_FULL = `SELECT ${D_COLS} ${D_FROM} WHERE r.id = ?`;
const dSelectMany = (n: number) =>
  `SELECT ${D_COLS} ${D_FROM} WHERE r.id IN (${placeholders(n)})`;
const D_SELECT_METADATA = `SELECT r.id AS id, b.mime_type AS mime_type, r.original_filename AS original_filename, b.size_bytes AS size_bytes, b.width AS width, b.height AS height, r.checksum_sha256 AS checksum_sha256 ${D_FROM} WHERE r.id = ?`;
const D_STREAM_INFO = `SELECT b.size_bytes AS size_bytes, 'sqlite' AS storage_backend, NULL AS object_storage_key ${D_FROM} WHERE r.id = ?`;
const D_CHUNK = `SELECT substr(b.data, ?, ?) AS chunk ${D_FROM} WHERE r.id = ?`;
const D_EXISTS = `SELECT 1 FROM zerobucket_image_refs WHERE id = ?`;
const D_DELETE_REF = `DELETE FROM zerobucket_image_refs WHERE id = ? RETURNING checksum_sha256`;
const dDeleteRefs = (n: number) =>
  `DELETE FROM zerobucket_image_refs WHERE id IN (${placeholders(n)}) RETURNING id, checksum_sha256`;
const D_DECREMENT = `UPDATE zerobucket_blobs SET ref_count = ref_count - ? WHERE checksum_sha256 = ? RETURNING ref_count`;
const D_DELETE_EMPTY = `DELETE FROM zerobucket_blobs WHERE checksum_sha256 = ? AND ref_count <= 0`;

/** SQLite's default max bound variables is 999 on old builds; stay well under it. */
const IN_CHUNK = 500;
/** Per-attempt busy wait inside the (synchronous) driver. Longer waits are done by async retry, never by blocking the loop. */
const ATTEMPT_BUSY_MS = 25;
export const DEFAULT_BUSY_TIMEOUT_MS = 10_000;

function placeholders(n: number): string {
  return Array.from({ length: n }, () => "?").join(", ");
}

/** Python-compatible ISO-8601 UTC with microseconds: 2026-10-03T12:00:00.123000+00:00 */
function isoNow(): string {
  return new Date().toISOString().replace("Z", "000+00:00");
}

function isBusy(exc: unknown): boolean {
  const code = (exc as { code?: unknown })?.code;
  return (
    typeof code === "string" &&
    (code.startsWith("SQLITE_BUSY") || code.startsWith("SQLITE_LOCKED"))
  );
}

/** The members of better-sqlite3's Database that this adapter uses beyond SqliteDatabaseLike. */
interface Db extends SqliteDatabaseLike {
  pragma(source: string, options?: { simple?: boolean }): unknown;
  close(): void;
}
type DbCtor = new (path: string, options?: { timeout?: number }) => Db;

/** Tiny async mutex: serializes in-process writers (and tiering) without blocking the event loop. */
class Mutex {
  private tail: Promise<void> = Promise.resolve();
  run<T>(fn: () => Promise<T>): Promise<T> {
    const prev = this.tail;
    let release!: () => void;
    this.tail = new Promise<void>((r) => (release = r));
    return prev.then(fn).finally(release);
  }
}

export interface SQLiteBackendOptions {
  /** Database file path, or ":memory:" for a throwaway in-process database (tiering is unavailable for ":memory:"). */
  path: string;
  /** Create the schema on first use. Default true. */
  autoMigrate?: boolean;
  /** Content-addressed mode (separate tables; same schema as the Python package). Cannot be combined with objectStorage. */
  dedup?: boolean;
  /** Enables tiering and transparent reads of tiered rows. */
  objectStorage?: ObjectStorageLike;
  /** Total time to keep retrying when another connection/process holds the write lock. Default 10000. */
  busyTimeoutMs?: number;
  onOperation?: (event: OperationEvent) => void;
}

export class SQLiteBackend implements StorageBackend {
  private db: Db | undefined;
  private Database: DbCtor | undefined;
  private readyPromise: Promise<void> | undefined;
  private closed = false;
  private readonly dedup: boolean;
  private readonly busyTimeoutMs: number;
  private readonly writeLock = new Mutex();

  constructor(private readonly opts: SQLiteBackendOptions) {
    if (!opts.path)
      throw new TypeError(
        'SQLiteBackend requires a `path` (a file path or ":memory:")',
      );
    this.dedup = opts.dedup ?? false;
    this.busyTimeoutMs = opts.busyTimeoutMs ?? DEFAULT_BUSY_TIMEOUT_MS;
    if (this.dedup && opts.objectStorage) {
      throw new TypeError(
        "objectStorage is not supported together with dedup: true (same restriction as the Python package). " +
          "Tiering moves one image's bytes, but a deduplicated blob can be shared by many images.",
      );
    }
  }

  // ---- lifecycle -------------------------------------------------------

  ready(): Promise<void> {
    if (this.closed)
      return Promise.reject(
        new StorageError("This ZeroBucket instance has been closed"),
      );
    this.readyPromise ??= this.init().catch((exc) => {
      this.readyPromise = undefined;
      throw exc;
    });
    return this.readyPromise;
  }

  private async init(): Promise<void> {
    try {
      const mod = (await import("better-sqlite3")) as unknown as {
        default?: DbCtor;
      } & DbCtor;
      this.Database = mod.default ?? mod;
    } catch (cause) {
      throw new StorageError(
        "SQLiteBackend requires the 'better-sqlite3' package. Install it with: npm install better-sqlite3",
        { cause },
      );
    }
    const db = new this.Database(this.opts.path, { timeout: ATTEMPT_BUSY_MS });
    try {
      await this.retrying(() => {
        // WAL is durable and file-level: only convert if the file is not already WAL (avoids needless
        // lock contention when many processes open the same fresh file at once).
        if (
          this.opts.path !== ":memory:" &&
          db.pragma("journal_mode", { simple: true }) !== "wal"
        ) {
          db.pragma("journal_mode = WAL");
        }
        db.pragma("foreign_keys = ON");
        if (this.opts.autoMigrate ?? true)
          db.exec(this.dedup ? DEDUP_SCHEMA : SCHEMA);
      });
    } catch (exc) {
      try {
        db.close();
      } catch {
        // ignore
      }
      throw new StorageError(
        `Could not open SQLite database ${JSON.stringify(this.opts.path)}: ${msg(exc)}`,
        { cause: exc },
      );
    }
    this.db = db;
  }

  async close(): Promise<void> {
    this.closed = true;
    const db = this.db;
    this.db = undefined;
    this.readyPromise = undefined;
    // let any in-flight write finish before the handle goes away
    await this.writeLock.run(async () => {
      db?.close();
    });
  }

  // ---- execution core --------------------------------------------------

  private emit(
    operation: string,
    start: number,
    success: boolean,
    error: string | null,
    retryCount: number,
  ): void {
    const cb = this.opts.onOperation;
    if (!cb) return;
    try {
      cb({
        operation,
        durationMs: performance.now() - start,
        success,
        error,
        retryCount,
      });
    } catch {
      // A bug in a metrics callback must never break a real operation.
    }
  }

  /** Re-run `fn` while another connection holds a lock, sleeping asynchronously between attempts. `fn` must be atomic. */
  private async retrying<T>(
    fn: () => T,
    onRetry?: (n: number) => void,
  ): Promise<T> {
    const deadline = performance.now() + this.busyTimeoutMs;
    let attempt = 0;
    for (;;) {
      try {
        return fn();
      } catch (exc) {
        if (!isBusy(exc) || performance.now() >= deadline) throw exc;
        attempt += 1;
        onRetry?.(attempt);
        await sleep(
          Math.min(5 * 2 ** Math.min(attempt, 5), 100) + Math.random() * 5,
        );
      }
    }
  }

  /** BEGIN IMMEDIATE takes the write lock up front, so a BUSY comes before any work and the whole unit is safely re-runnable. */
  private tx<T>(db: Db, work: (db: Db) => T): T {
    db.exec("BEGIN IMMEDIATE");
    try {
      const result = work(db);
      db.exec("COMMIT");
      return result;
    } catch (exc) {
      try {
        db.exec("ROLLBACK");
      } catch {
        // keep the original error
      }
      throw exc;
    }
  }

  /**
   * All-or-nothing work on a CALLER-supplied handle. SAVEPOINT works whether or not the caller has an open
   * transaction: inside one it nests (a failure rolls back only our work); outside one it begins and, on
   * RELEASE, commits.
   */
  private atomic<T>(db: Db, work: (db: Db) => T): T {
    db.exec("SAVEPOINT zerobucket_atomic");
    try {
      const result = work(db);
      db.exec("RELEASE SAVEPOINT zerobucket_atomic");
      return result;
    } catch (exc) {
      try {
        db.exec("ROLLBACK TO SAVEPOINT zerobucket_atomic");
        db.exec("RELEASE SAVEPOINT zerobucket_atomic");
      } catch {
        // keep the original error
      }
      throw exc;
    }
  }

  private async execute<T>(
    operation: string,
    connection: Connection | undefined,
    mode: "read" | "write",
    work: (db: Db) => T,
  ): Promise<T> {
    const start = performance.now();
    let retries = 0;
    try {
      let result: T;
      if (connection) {
        if (typeof (connection as SqliteDatabaseLike).prepare !== "function") {
          throw new TypeError(
            "SQLiteBackend expects a better-sqlite3 Database as `connection` (an object with prepare()), not a pg client.",
          );
        }
        const db = connection as Db;
        result = mode === "write" ? this.atomic(db, work) : work(db);
      } else {
        await this.ready();
        const db = this.db!;
        const onRetry = (n: number) => (retries = n);
        result =
          mode === "write"
            ? await this.writeLock.run(() =>
                this.retrying(() => this.tx(db, work), onRetry),
              )
            : await this.retrying(() => work(db), onRetry);
      }
      this.emit(operation, start, true, null, retries);
      return result;
    } catch (exc) {
      this.emit(operation, start, false, msg(exc), retries);
      throw exc;
    }
  }

  // ---- StorageBackend --------------------------------------------------

  async put(
    row: PreparedRow,
    { connection }: CallOptions = {},
  ): Promise<string> {
    try {
      return await this.execute("put", connection, "write", (db) =>
        this.insertOne(db, row),
      );
    } catch (exc) {
      throw wrap("Failed to store image", exc);
    }
  }

  private insertOne(db: Db, r: PreparedRow): string {
    const id = randomUUID();
    const now = isoNow();
    if (this.dedup) {
      db.prepare(D_UPSERT).run(
        r.checksumSha256,
        r.data,
        r.mimeType,
        r.sizeBytes,
        r.width,
        r.height,
        1,
        now,
      );
      db.prepare(D_INSERT_REF).run(
        id,
        r.checksumSha256,
        r.originalFilename,
        now,
        now,
      );
    } else {
      db.prepare(INSERT).run(
        id,
        r.data,
        r.mimeType,
        r.originalFilename,
        r.sizeBytes,
        r.width,
        r.height,
        r.checksumSha256,
        now,
        now,
      );
    }
    return id;
  }

  async putMany(
    rows: PreparedRow[],
    { connection }: CallOptions = {},
  ): Promise<string[]> {
    if (rows.length === 0) return [];
    try {
      return await this.execute("put_many", connection, "write", (db) => {
        if (!this.dedup) return rows.map((r) => this.insertOne(db, r));
        // Identical images in one batch share a blob: count them and upsert each distinct checksum once.
        const now = isoNow();
        const groups = new Map<string, { row: PreparedRow; n: number }>();
        for (const r of rows) {
          const g = groups.get(r.checksumSha256);
          if (g) g.n += 1;
          else groups.set(r.checksumSha256, { row: r, n: 1 });
        }
        for (const [checksum, { row, n }] of groups) {
          db.prepare(D_UPSERT).run(
            checksum,
            row.data,
            row.mimeType,
            row.sizeBytes,
            row.width,
            row.height,
            n,
            now,
          );
        }
        return rows.map((r) => {
          const id = randomUUID();
          db.prepare(D_INSERT_REF).run(
            id,
            r.checksumSha256,
            r.originalFilename,
            now,
            now,
          );
          return id;
        });
      });
    } catch (exc) {
      throw wrap("Failed to store image batch", exc);
    }
  }

  async get(
    id: string,
    { connection }: CallOptions = {},
  ): Promise<StoredRecord | null> {
    if (!isValidId(id)) return null;
    const norm = id.toLowerCase();
    let row: any;
    try {
      row = await this.execute("get", connection, "read", (db) =>
        db.prepare(this.dedup ? D_SELECT_FULL : SELECT_FULL).get(norm),
      );
    } catch (exc) {
      throw wrap("Failed to retrieve image", exc);
    }
    return row ? hydrateRow(row, norm, this.opts.objectStorage) : null;
  }

  async getMany(
    ids: string[],
    { connection }: CallOptions = {},
  ): Promise<StoredRecord[]> {
    const valid = [
      ...new Set(ids.filter(isValidId).map((i) => i.toLowerCase())),
    ];
    if (valid.length === 0) return [];
    let rows: any[];
    try {
      rows = await this.execute("get_many", connection, "read", (db) => {
        const out: any[] = [];
        for (let i = 0; i < valid.length; i += IN_CHUNK) {
          const part = valid.slice(i, i + IN_CHUNK);
          out.push(
            ...db
              .prepare(
                this.dedup ? dSelectMany(part.length) : selectMany(part.length),
              )
              .all(...part),
          );
        }
        return out;
      });
    } catch (exc) {
      throw wrap("Failed to retrieve image batch", exc);
    }
    return mapLimit(rows, 4, (r) =>
      hydrateRow(r, String(r.id), this.opts.objectStorage),
    );
  }

  async getMetadata(
    id: string,
    { connection }: CallOptions = {},
  ): Promise<StoredRecordMetadata | null> {
    if (!isValidId(id)) return null;
    let row: any;
    try {
      row = await this.execute("get_metadata", connection, "read", (db) =>
        db
          .prepare(this.dedup ? D_SELECT_METADATA : SELECT_METADATA)
          .get(id.toLowerCase()),
      );
    } catch (exc) {
      throw wrap("Failed to retrieve image metadata", exc);
    }
    if (!row) return null;
    return {
      id: String(row.id),
      mimeType: row.mime_type,
      originalFilename: row.original_filename,
      sizeBytes: row.size_bytes,
      width: row.width,
      height: row.height,
      checksumSha256: row.checksum_sha256,
    };
  }

  async getStream(
    id: string,
    opts: StreamOptions,
  ): Promise<AsyncIterable<Buffer> | null> {
    if (!isValidId(id)) return null;
    const norm = id.toLowerCase();
    const { connection, chunkSize } = opts;
    if (!Number.isInteger(chunkSize) || chunkSize <= 0)
      throw new RangeError("chunkSize must be a positive integer");

    let info: any;
    try {
      info = await this.execute("get_metadata", connection, "read", (db) =>
        db.prepare(this.dedup ? D_STREAM_INFO : STREAM_INFO).get(norm),
      );
    } catch (exc) {
      throw wrap("Failed to retrieve image metadata", exc);
    }
    if (!info) return null;

    const totalSize: number = info.size_bytes;
    const start = opts.range?.start ?? 0;
    const end = Math.min(opts.range?.end ?? totalSize - 1, totalSize - 1); // inclusive, clamped

    if (info.storage_backend === "object_storage") {
      const os = this.opts.objectStorage;
      if (!os) throw tieredWithoutStorage(norm, info.object_storage_key);
      return streamFromObjectStorage(
        os,
        norm,
        info.object_storage_key,
        start,
        end,
        chunkSize,
      );
    }

    const self = this;
    async function* generate(): AsyncGenerator<Buffer> {
      let offset = start;
      let delivered = 0;
      const wanted = Math.max(0, end - start + 1);
      while (delivered < wanted) {
        const length = Math.min(chunkSize, wanted - delivered);
        let row: any;
        try {
          row = await self.execute("get_stream", connection, "read", (db) =>
            db
              .prepare(self.dedup ? D_CHUNK : CHUNK)
              .get(offset + 1, length, norm),
          );
        } catch (exc) {
          throw wrap("Failed to stream image", exc);
        }
        if (!row) {
          throw new StorageError(
            `Image ${JSON.stringify(norm)} was deleted while streaming (delivered ${delivered} of ${wanted} bytes). ` +
              "Pass connection with your own open transaction if you need a consistent read across concurrent writers.",
          );
        }
        const chunk: Buffer | null = row.chunk;
        if (!chunk || chunk.length === 0) {
          throw new StorageError(
            `Image ${JSON.stringify(norm)} ended early while streaming (delivered ${delivered} of ${wanted} bytes).`,
          );
        }
        yield chunk;
        offset += chunk.length;
        delivered += chunk.length;
      }
    }
    return generate();
  }

  async delete(id: string, { connection }: CallOptions = {}): Promise<boolean> {
    if (!isValidId(id)) return false;
    const norm = id.toLowerCase();
    try {
      if (this.dedup) {
        return await this.execute("delete", connection, "write", (db) => {
          const ref = db.prepare(D_DELETE_REF).get(norm);
          if (!ref) return false;
          const dec = db.prepare(D_DECREMENT).get(1, ref.checksum_sha256);
          if (dec && dec.ref_count <= 0)
            db.prepare(D_DELETE_EMPTY).run(ref.checksum_sha256);
          return true;
        });
      }
      const row = await this.execute("delete", connection, "write", (db) =>
        db.prepare(DELETE_ONE).get(norm),
      );
      if (row?.storage_backend === "object_storage")
        await this.cleanupObjects([row.object_storage_key], connection);
      return row !== undefined;
    } catch (exc) {
      throw wrap("Failed to delete image", exc);
    }
  }

  async deleteMany(
    ids: string[],
    { connection }: CallOptions = {},
  ): Promise<string[]> {
    const valid = [
      ...new Set(ids.filter(isValidId).map((i) => i.toLowerCase())),
    ];
    if (valid.length === 0) return [];
    try {
      if (this.dedup) {
        return await this.execute("delete_many", connection, "write", (db) => {
          const deleted: { id: string; checksum_sha256: string }[] = [];
          for (let i = 0; i < valid.length; i += IN_CHUNK) {
            const part = valid.slice(i, i + IN_CHUNK);
            deleted.push(...db.prepare(dDeleteRefs(part.length)).all(...part));
          }
          const counts = new Map<string, number>();
          for (const r of deleted)
            counts.set(
              r.checksum_sha256,
              (counts.get(r.checksum_sha256) ?? 0) + 1,
            );
          for (const [checksum, n] of counts) {
            const dec = db.prepare(D_DECREMENT).get(n, checksum);
            if (dec && dec.ref_count <= 0)
              db.prepare(D_DELETE_EMPTY).run(checksum);
          }
          return deleted.map((r) => String(r.id));
        });
      }
      const rows = await this.execute(
        "delete_many",
        connection,
        "write",
        (db) => {
          const out: any[] = [];
          for (let i = 0; i < valid.length; i += IN_CHUNK) {
            const part = valid.slice(i, i + IN_CHUNK);
            out.push(...db.prepare(deleteMany(part.length)).all(...part));
          }
          return out;
        },
      );
      await this.cleanupObjects(
        rows
          .filter((r) => r.storage_backend === "object_storage")
          .map((r) => r.object_storage_key as string),
        connection,
      );
      return rows.map((r) => String(r.id));
    } catch (exc) {
      throw wrap("Failed to delete image batch", exc);
    }
  }

  async exists(id: string, { connection }: CallOptions = {}): Promise<boolean> {
    if (!isValidId(id)) return false;
    try {
      return await this.execute(
        "exists",
        connection,
        "read",
        (db) =>
          db.prepare(this.dedup ? D_EXISTS : EXISTS).get(id.toLowerCase()) !==
          undefined,
      );
    } catch (exc) {
      throw wrap("Failed to check image existence", exc);
    }
  }

  /**
   * Remove tiered objects AFTER their rows are gone (a failed object delete leaves a harmless orphan; the
   * reverse order could leave a row pointing at nothing). Skipped inside a caller-owned transaction, since the
   * commit outcome is unknown. Failures never fail the delete; they are reported through onOperation.
   */
  private async cleanupObjects(
    keys: string[],
    connection: Connection | undefined,
  ): Promise<void> {
    const os = this.opts.objectStorage;
    if (!os || connection || keys.length === 0) return;
    await Promise.all(
      keys.map(async (key) => {
        const start = performance.now();
        try {
          await os.delete(key);
          this.emit("object_storage_delete", start, true, null, 0);
        } catch (exc) {
          this.emit("object_storage_delete", start, false, msg(exc), 0);
        }
      }),
    );
  }

  /**
   * Move an image's bytes into object storage. null = no such image, false = already tiered, true = tiered now.
   *
   * SAFETY (same guarantee as Postgres): the upload happens INSIDE a BEGIN IMMEDIATE transaction; if it fails the
   * transaction rolls back and the row is untouched.
   *
   * TRADEOFF (coarser than Postgres): SQLite has no row locks, so BEGIN IMMEDIATE locks the WHOLE DATABASE for the
   * upload. Other processes' writes wait; this process's writes queue behind an async lock; reads are not blocked.
   */
  async tierToObjectStorage(
    id: string,
    { connection }: CallOptions = {},
  ): Promise<boolean | null> {
    if (this.dedup)
      throw new StorageError(
        "tierToObjectStorage() is not supported in dedup mode (a blob may be shared by many images).",
      );
    const os = this.opts.objectStorage;
    if (!os) {
      throw new StorageError(
        "tierToObjectStorage() requires objectStorage to be configured (new ZeroBucket({ sqlite, objectStorage: new ObjectStorage({ bucket }) })).",
      );
    }
    if (connection) {
      throw new StorageError(
        "tierToObjectStorage() does not accept `connection` on SQLite: it needs its own dedicated connection for the BEGIN IMMEDIATE transaction.",
      );
    }
    if (this.opts.path === ":memory:") {
      throw new StorageError(
        "tierToObjectStorage() needs a database file: an in-memory SQLite database cannot be shared with its dedicated tiering connection.",
      );
    }
    if (!isValidId(id)) return null;
    const norm = id.toLowerCase();
    const start = performance.now();
    let retries = 0;
    try {
      await this.ready();
      const result = await this.writeLock.run(async () => {
        const tdb = new this.Database!(this.opts.path, {
          timeout: ATTEMPT_BUSY_MS,
        });
        try {
          await this.retrying(
            () => tdb.exec("BEGIN IMMEDIATE"),
            (n) => (retries = n),
          );
          try {
            const row = tdb.prepare(SELECT_FOR_TIERING).get(norm);
            if (!row) {
              tdb.exec("ROLLBACK");
              return null;
            }
            if (row.storage_backend !== "sqlite") {
              tdb.exec("ROLLBACK");
              return false;
            }
            await os.upload(norm, row.data as Buffer, {
              mimeType: row.mime_type,
            });
            tdb
              .prepare(UPDATE_AFTER_TIERING)
              .run(os.bucket, norm, isoNow(), norm);
            tdb.exec("COMMIT");
            return true;
          } catch (exc) {
            try {
              tdb.exec("ROLLBACK");
            } catch {
              // keep the original error
            }
            throw exc;
          }
        } finally {
          tdb.close();
        }
      });
      this.emit("tier_to_object_storage", start, true, null, retries);
      return result;
    } catch (exc) {
      this.emit("tier_to_object_storage", start, false, msg(exc), retries);
      throw wrap("Failed to tier image to object storage", exc);
    }
  }
}
