# Generated by Django 6.1.1 on 2026-09-04 07:59

from django.db import migrations, models

import django_zerobucket.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        storage=django_zerobucket.storage.ZeroBucketStorage,
                        upload_to="ignored",
                    ),
                ),
            ],
        ),
    ]
